name: $(moduleName)-$(moduleVersion)

variables:
- template: pipeline.variables.yml

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - Modules/EventHubs/*
    exclude:
    - Modules/EventHubs/*/readme.md
    
stages:

- stage: Validate
  jobs:
  - template: pipeline.jobs.validate.yml
    parameters:
      templateFile: $(modulePath)/deploy.json
      parametersFile: $(modulePath)/Parameters/parameters.json

- stage: Deploy
  jobs:
  - template: pipeline.jobs.deploy.yml
    parameters:
      templateFile: $(modulePath)/deploy.json
      parametersFile: $(modulePath)/Parameters/parameters.json

- stage: Publish_Artifact
  jobs:
  - template: pipeline.jobs.publish.yml
