parameters:
  connectionService: ''
  deploymentBlocks: ''
  resourceGroup: $(resourceGroup)
  location: $(location)
  overrideParameters: $(overrideParameters)
  dependsOn: ''
  condition: ''
  source: ''
  subscriptionId: ["teste"]
  deploymentScope: $(deploymentScope)
  enabled: succeeded()

  # Azure PowerShell Version parameters
  azurePowerShellVersion: '$(azurePowerShellVersion)'
  preferredAzurePowerShellVersion: '$(preferredAzurePowerShellVersion)'

jobs:
- ${{ each connectionService in parameters.connectionService }}:
  - ${{ each deploymentBlock in parameters.deploymentBlocks }}:
    - job:
      displayName: '${{ deploymentBlock.displayname }} - ${{ connectionService }}'
      condition: ${{ parameters.enabled }}
      pool:
        vmImage: $(poolName)

      dependsOn: '${{ deploymentBlock.dependsOn }}'

      steps:
        - task: CopyFiles@2
          displayName: Filter folders
          inputs:
            contents: '**'
            targetFolder: $(Build.ArtifactStagingDirectory)
        - task: AzurePowerShell@5
          displayName: 'Get Azure SubscriptionId'
          inputs:
            azureSubscription: '${{ connectionService }}'
            ScriptType: 'InlineScript'
            Inline: |
              $sub = (Get-AzSubscription).SubscriptionId
              foreach ($i in $sub) {
                Write-Host "printing"$i
                Write-Host "printing"$j
                Set-AzContext $i
                $subName = ((Get-AzContext).Subscription).name
                Write-Host "##vso[task.setvariable variable=subscriptionName;]$subName"
                if('${{ parameters.deploymentScope }}' -eq 'Subscription'){New-AzDeployment -Name $(Get-Random) -Location 'Brazil South' -TemplateFile '$(Build.ArtifactStagingDirectory)/${{ deploymentBlock.path }}/template.json' -TemplateParameterFile '$(Build.ArtifactStagingDirectory)/${{ deploymentBlock.path }}/parameters.json'}
                if('${{ parameters.deploymentScope }}' -eq "Resource Group"){New-AzResourceGroupDeployment -Name $(Get-Random) -ResourceGroupName '${{parameters.resourceGroup}}' -TemplateFile '$(Build.ArtifactStagingDirectory)/${{ deploymentBlock.path }}/template.json' -TemplateParameterFile '$(Build.ArtifactStagingDirectory)/${{ deploymentBlock.path }}/parameters.json'}
              }

              
            azurePowerShellVersion: latestVersion