parameters:
  deploymentBlocks: ''
  connectionService: ''
  resourceGroup: $(resourceGroup)
  location: $(location)
  overrideParameters: $(overrideParameters)
  dependsOn: ''
  condition: ''
  # Azure PowerShell Version parameters
  azurePowerShellVersion: '$(azurePowerShellVersion)'
  preferredAzurePowerShellVersion: '$(preferredAzurePowerShellVersion)'

jobs:
- ${{ each connectionService in parameters.connectionService }}:
  - ${{ each deploymentBlock in parameters.deploymentBlocks }}:
    - job:
      displayName: '${{ deploymentBlock.displayname }}'
      condition: succeeded()
      pool:
        vmImage: $(poolName)

      steps:
        - task: CopyFiles@2
          displayName: Filter folders
          inputs:
            contents: '**'
            targetFolder: $(Build.ArtifactStagingDirectory)

        - task: AzurePowerShell@5
          displayName: 'Deploy ${{ parameters.moduleName }}'
          inputs:
            azureSubscription: '${{ connectionService }}'
            ScriptType: 'InlineScript'
            Inline: |
              $PolicySetDefinition = New-AzPolicySetDefinition -Name '${{deploymentBlock.categoria}}' -ManagementGroupName Lab -Metadata '{"category":"${{deploymentBlock.categoria}}"}' -PolicyDefinition $(Build.ArtifactStagingDirectory)/${{ deploymentBlock.path }}/PolicySet.json
              Set-AzPolicySetDefinition -Id $PolicySetDefinition.ResourceId -Description 'Updated policy'
            azurePowerShellVersion: latestVersion