name: blueprint

variables:
- template: variables.yaml

- name: pipelineCustomVersion
  value: 1.0.0

trigger:
  batch: true
  branches:
    include:
    - mstest
  paths:
    include:
    - Modules/*
    - Blueprint/*

stages:
- stage: Deployment
  jobs:
  - template: /Blueprint/deployPolicyInitiative.yaml
    parameters:
      connectionService: 
      - mstest
      deploymentBlocks:
      - path: Modules/Policy/Initiative/AppService
        displayname: Policy Initiative AppService
        categoria: AppService

      - path: Modules/Policy/Initiative/DatabaseServices
        displayname: Policy Initiative DBServices
        categoria: Database Services

      - path: Modules/Policy/Initiative/Identity
        displayname: Policy Initiative Identity
        categoria: Identitity and Access Management

      - path: Modules/Policy/Initiative/Logging&Monitoring
        displayname: Policy Initiative Logg & Monitor
        categoria: Logging and Monitoring

      - path: Modules/Policy/Initiative/Networking
        displayname: Policy Initiative Networking
        categoria: Networking

      - path: Modules/Policy/Initiative/OtherSecurity
        displayname: Policy Initiative Other Security
        categoria: Security

      - path: Modules/Policy/Initiative/SecurityCenter
        displayname: Policy Initiative SecurityCenter
        categoria: SecurityCenter  

      - path: Modules/Policy/Initiative/Storage
        displayname: Policy Initiative Storage
        categoria: Storage
        
      - path: Modules/Policy/Initiative/VirtualMachine
        displayname: Policy Initiative VM
        categoria: Virtual Machine
