name: blueprint

variables:
- template: variables.yaml

- name: pipelineCustomVersion
  value: 1.0.0

trigger:
  batch: true
  branches:
    include:
    - mstest
  paths:
    include:
    - Modules/*
    - Blueprint/*

stages:
- stage: Deployment
  jobs:
  - template: /Blueprint/deployPolicyDefinition.yaml
    parameters:
      connectionService: 
      - mstest
      deploymentBlocks:
      - path: Modules/Policy/Tag
        displayname: Policy Definition
