name: blueprint

variables:
- template: variables.yaml

- name: pipelineCustomVersion
  value: 1.0.0

trigger:
  batch: true
  branches:
    include:
    - mstest
  paths:
    include:
    - Modules/*
    - Blueprint/*

stages:
- stage: Deployment
  jobs:
  - template: /Blueprint/deploy.yaml
    parameters:
      deploymentScope: Subscription
      source: resource
      connectionService: 
      - Azure-LandingZone-to-Proj-00000
      deploymentBlocks:
      - path: Modules/ResourceGroups/V1
        displayname: ResourceGroup Deployment

      - path: Modules/Diagnostics/SubscriptionActivityLog
        displayname: Diag Event Hub Deployment
        dependsOn: Job1

  - template: /Blueprint/deploy.yaml
    parameters:
      deploymentScope: Resource Group
      source: resource
      connectionService: 
      - Azure-LandingZone-to-Proj-00000
      deploymentBlocks:
      - path: Modules/network/NSG
        displayname: NSG Deployment
        dependsOn: Job2

      - path: Modules/network/UDR
        displayname: UDR Deployment
        dependsOn: Job3

      - path: Modules/network/VNET
        displayname: VNET Deployment
        dependsOn: Job4

      - path: Modules/Backup_V2/Vault
        displayname: BackupVault Deployment
        dependsOn: Job5