name: blueprint

variables:
- template: variables.yaml

- name: pipelineCustomVersion
  value: 1.0.0

trigger:
  batch: true
  branches:
    include:
    - mstest
  paths:
    include:
    - Modules/*
    - Blueprint/*

stages:
- stage: Deployment
  jobs:
  - template: /Blueprint/deployloop.yaml
    parameters:
      deploymentScope: Subscription
      source: resource
      connectionService: 
      - mstest-loop
      deploymentBlocks:
      - path: Modules/ResourceGroups/v0
        displayname: ResourceGroup Deployment
    
  - template: /Blueprint/deployloop.yaml
    parameters:
      deploymentScope: Resource Group
      source: resource
      connectionService: 
      - mstest-loop
      deploymentBlocks:
      - path: Modules/network/NSG
        displayname: NSG Deployment
        dependsOn: Job1

      - path: Modules/network/UDR
        displayname: UDR Deployment
        dependsOn: Job2

      - path: Modules/network/VNET
        displayname: VNET Deployment
        dependsOn: Job3