parameters:
  moduleName: 

jobs:
- job: Publish_Artifact
  pool:
    # name: $(PoolName)
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: PublishBuildArtifacts@1
      displayName: Publish $(moduleName) Artifacts
      inputs:
        PathtoPublish: $(modulePath)
        ArtifactName: $(moduleName)-$(moduleVersion)
- job: Copy_Artifact_To_Storage_Account
  pool:
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: CopyFiles@2
      displayName: Filter folders
      inputs:
        Contents: |
          Modules/$(moduleName)/$(moduleVersion)/**
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: AzureCLI@1
      displayName: Copy module components to Azure storage account
      inputs:
        azureSubscription: $(serviceConnection)
        scriptLocation: inlineScript
        inlineScript: |
            az storage container create --name          "$(componentStorageContainerName)" \
                                        --public-access off \
                                        --account-name  "$(componentStorageAccountName)" \
                                        --subscription  "$(componentStorageAccountSubscriptionId)"
                                        
            az storage blob sync --container    "$(componentStorageContainerName)" \
                                 --source       "$(Build.ArtifactStagingDirectory)/Modules/$(moduleName)/$(moduleVersion)" \
                                 --destination  "Modules/$(moduleName)/$(moduleVersion)" \
                                 --account-name "$(componentStorageAccountName)" \
                                 --subscription  "$(componentStorageAccountSubscriptionId)"