parameters:
  moduleName: 
  templateFile: $(modulePath)/deploy.json
  parametersFile: $(modulePath)/Tests/parameters.json
  
jobs:
- job: DeployModule
  pool:
    # name: $(poolName)
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: AzurePowerShell@4
      displayName: Deploy $(moduleName)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        inline: |
            $Location = "$(location)" -replace " ",""

            $DeploymentInputs = @{
              Name                  = "$(moduleName)-$(moduleVersion)"
              TemplateFile          = "$(Build.Repository.LocalPath)/${{ parameters.templateFile }}"
              TemplateParameterFile = "$(Build.Repository.LocalPath)/${{ parameters.parametersFile }}"
              Location              = $Location
              Verbose               = $true
              ErrorAction          = "Stop"
            }
            
            New-AzDeployment @DeploymentInputs
        azurePowerShellVersion: LatestVersion
