parameters:
  moduleName: 
  templateFile: $(modulePath)/deploy.json
  parametersFile: $(modulePath)/Tests/parameters.json

jobs:
- job: ValidateModule
  pool:
    # name: $(PoolName)
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: PowerShell@2
      displayName: Test Module $(moduleName) (Pester)
      inputs:
        targetType: inline
        script: |
          Install-Module Pester -Force -ErrorAction Stop

          $PesterSettings  = @{
            Script       = "$(System.DefaultWorkingDirectory)/$(modulePath)/Tests/*.tests.ps1"
            OutputFile   = "$(Agent.WorkFolder)/testsresult.xml"
            OutputFormat = "NUnitXml"
            EnableExit   = $true
            Verbose      = $true
          }

          Invoke-Pester @PesterSettings
          
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: $(Agent.WorkFolder)/testsresult.xml

    - task: AzurePowerShell@4
      displayName: Validate $(moduleName) on $(resourceGroupName)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        inline: |
          $ValidationErrors = $null

          $Location = "$(location)" -replace " ",""

          $DeploymentInputs = @{
            Location              = "$Location"
            TemplateFile          = "$(Build.Repository.LocalPath)/${{ parameters.templateFile }}"
            TemplateParameterFile = "$(Build.Repository.LocalPath)/${{ parameters.parametersFile }}"
            Verbose               = $true
            OutVariable           = "ValidationErrors"
          }
          
          Test-AzDeployment @DeploymentInputs

          if ($ValidationErrors)
          {
            Write-Error "Template is not valid."
          }
        azurePowerShellVersion: LatestVersion
