parameters:
  moduleName: 
  templateFile: $(modulePath)/deploy.json
  parametersFile: $(modulePath)/Tests/parameters.json
  
jobs:
- job: DeployModule
  pool:
    # name: $(poolName)
    vmImage: $(vmImage)
  variables:
  - template: pipeline.variables.yml
  steps:
    - task: AzurePowerShell@4
      displayName: Deploy $(moduleName) on $(resourceGroupName)
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptType: InlineScript
        inline: |
            if (-not (Get-AzResourceGroup -Name $(resourceGroupName) -ErrorAction SilentlyContinue))
            {
              $Location = "$(location)" -replace " ",""
              New-AzResourceGroup -Name $(resourceGroupName) -Location $Location
            }

            $adminPassword = ConvertTo-SecureString -String "$(adminPassword)" -AsPlainText -Force

            $DeploymentInputs = @{
              Name                  = "$(moduleName)-$(moduleVersion)"
              ResourceGroupName     = "$(resourceGroupName)"
              TemplateFile          = "$(Build.Repository.LocalPath)/${{ parameters.templateFile }}"
              TemplateParameterFile = "$(Build.Repository.LocalPath)/${{ parameters.parametersFile }}"
              Mode                  = "Incremental"
              Verbose               = $true
              ErrorAction           = "Stop"
              adminPassword         = $adminPassword
            }
            
            New-AzResourceGroupDeployment @DeploymentInputs
        azurePowerShellVersion: LatestVersion
