# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
        
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
         # Specify the Az PowerShell script here.
          inlineScript:
            Set-AzContext -Subscription 3a7b2a57-6a18-4d6a-8612-5ca185384ecd
            |New-AzPolicyDefinition -Name "deny-nsg-inbound-management-anytoany3" -DisplayName "Denies NSG rule changes that allow inbound management traffic any to any" -description "Denies people from changing NSG rules that allow inbound managemenet any to any traffic" -Policy '.\RulesManagemenet.json' -Mode All
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: 
            latest
          # Select the value of the ErrorActionPreference variable for executing the script. Options: stop, continue, silentlyContinue. Default is Stop.
          errorActionPreference: # optional, default is Stop
            Stop
          # If this is true, this task will fail if any errors are written to the error pipeline, or if any data is written to the Standard Error stream.
